name: sathi4life
description: A smart matchmaking app for Nepal.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  image_picker: ^1.1.1
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.1.5
  google_fonts: ^6.2.1
  connectivity_plus: ^4.0.1
  permission_handler: ^11.3.1
  lottie: ^2.7.0
  flutter_svg: ^2.0.7
  shimmer: ^3.0.0
  swipe_cards: ^2.0.0+1
  flutter_native_splash: ^2.3.10


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/default_profile.png
    - assets/google_signIn_logo.svg
    - assets/welcome_page.png
    - assets/match.json
    - assets/logo_heart.png
    - assets/app_icon_foreground.png
    - assets/background.jpg

flutter_icons:
  android:  true
  ios:  true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#FF0000"
  adaptive_icon_foreground: "assets/app_icon_foreground.png"

