// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHn8rwZPgS_nOdLPQyX4l3kTdZyYsTOvo',
    appId: '1:176534616190:web:287eb6a1e425990d2a402f',
    messagingSenderId: '176534616190',
    projectId: 'sathi4life-new',
    authDomain: 'sathi4life-new.firebaseapp.com',
    storageBucket: 'sathi4life-new.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCylmGbpVqElho8hyr88crpAPiaOLa1i3E',
    appId: '1:176534616190:android:ac1d0fbcb4da5f332a402f',
    messagingSenderId: '176534616190',
    projectId: 'sathi4life-new',
    storageBucket: 'sathi4life-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwDIm1lQYAczq0cptlzyhXw-HZtgOD35M',
    appId: '1:176534616190:ios:0d171891dbf862e02a402f',
    messagingSenderId: '176534616190',
    projectId: 'sathi4life-new',
    storageBucket: 'sathi4life-new.firebasestorage.app',
    iosBundleId: 'com.sathi4life',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwDIm1lQYAczq0cptlzyhXw-HZtgOD35M',
    appId: '1:176534616190:ios:0d171891dbf862e02a402f',
    messagingSenderId: '176534616190',
    projectId: 'sathi4life-new',
    storageBucket: 'sathi4life-new.firebasestorage.app',
    iosBundleId: 'com.sathi4life',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHn8rwZPgS_nOdLPQyX4l3kTdZyYsTOvo',
    appId: '1:176534616190:web:b7f44e302555d4f62a402f',
    messagingSenderId: '176534616190',
    projectId: 'sathi4life-new',
    authDomain: 'sathi4life-new.firebaseapp.com',
    storageBucket: 'sathi4life-new.firebasestorage.app',
  );

}